### ISSUE TITLE
Try to load a website that doesn't exist → spoof-dpi crashes

### ISSUE THREAD

**Issue by reolcor** [xvzc/SpoofDPI#15]
Spoof-dpi crashes when try to load a website that doesn't exist (or website maybe goes offline).

```
CONNECT www.matchacha.ro:443 HTTP/1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: www.matchacha.ro:443
 
panic: runtime error: index out of range [0] with length 0

goroutine 55 [running]:
github.com/xvzc/SpoofDPI/doh.Lookup({0xc0000946f8, 0x5})
	/SpoofDPI/doh/dns.go:22 +0x6e
github.com/xvzc/SpoofDPI/net.(*Conn).HandleHttps(0xc00023ecb0, {{0xc000294820, 0xcf, 0xd0}, {0xc0000946f0, 0x7}, {0xc0000946f8, 0x10}, {0xc000094708, 0x4}, ...})
	/SpoofDPI/net/conn.go:125 +0xaf
github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start.func1()
	/SpoofDPI/proxy/proxy.go:59 +0x167
created by github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start
	/SpoofDPI/proxy/proxy.go:43 +0x2bb
```

**Comment by xvzc** [comment]
thx

**Comment by xvzc** [comment]
fixed. closing
